pipeline {
  agent { docker { image: 'node:latest' }}
  stages {
    stage('test') {
      steps {
        sh 'npm test'
      }
    }
    stage('deploy') {
      when('master')
      steps {
        pushToCloudFoundry({

        })
      }
    }
  }
}
