pipeline {
  agent: { docker: { image: 'node:latest' }}
  stages: {
    stage('setup') {
      steps {
        sh 'npm i yarn -g'
      }
    }
    stage('build') {
      steps {
        sh 'yarn build'
      }
    }
    stage('test') {
      steps {
        sh 'yarn test'
      }
    }
    stage('deploy') {
      when('master')
      steps {
        pushToCloudFoundry({
        
        })
      }
    }
  }

}
