pipeline {
  agent { docker: { image: 'node:latest' }}
  stages {
    stage('setup') {
      steps {
        sh 'npm i yarn -g'
      }
    }
    stage('build') {
      steps {
        sh 'yarn build'
      }
    }
    stage('test') {
      steps {
        sh 'yarn test'
      }
    }
    stage('deploy') {
      when('master')
      steps {
       pushToCloudFoundry(
          target: 'api.run.pivotal.io',
          organization: 'twilson63',
          cloudSpace: 'development',
          credentialsId: 'twilson63-pivotal'
        ) 
      }
    }
  }

}
